version: "2.3"

services:
  postgresql-db:
    image: postgres:12.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
    - 5432:5432
    networks:
    - turreta_network
    volumes:
    - db-data:/var/lib/postgresql/data

networks:
  turreta_network:
    driver: bridge

volumes:
  db-data:
    driver: local 
